### ISSUE TITLE
Error when a model contains a column_property

### ISSUE THREAD

**Issue by ThiefMaster** [marshmallow-code/marshmallow-sqlalchemy#97]
```python
from marshmallow_sqlalchemy import ModelSchema
from sqlalchemy import *
from sqlalchemy.ext.declarative import declared_attr, declarative_base
from sqlalchemy.orm import *

Base = declarative_base()


class Foo(Base):
    __tablename__ = 'foo'
    id = Column(Integer, primary_key=True)

    @declared_attr
    def moo(self):
        return column_property(select([1337]))


e = create_engine('sqlite:///')
Base.metadata.create_all(e)
s = Session(e)

s.add(Foo())
s.commit()

foo = s.query(Foo).first()
print foo.moo


class FooSchema(ModelSchema):
    class Meta:
        model = Foo
```

Traceback

```python
Traceback (most recent call last):
  File "satest.py", line 29, in <module>
    class FooSchema(ModelSchema):
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow/schema.py", line 116, in __new__
    dict_cls=dict_cls
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow_sqlalchemy/schema.py", line 60, in get_declared_fields
    declared_fields = mcs.get_fields(converter, opts, base_fields, dict_cls)
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow_sqlalchemy/schema.py", line 94, in get_fields
    dict_cls=dict_cls,
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 105, in fields_for_model
    field = base_fields.get(prop.key) or self.property2field(prop)
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 125, in property2field
    field_class = field_class or self._get_field_class_for_property(prop)
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 186, in _get_field_class_for_property
    field_cls = self._get_field_class_for_column(column)
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 153, in _get_field_class_for_column
    return self._get_field_class_for_data_type(column.type)
  File "/home/adrian/dev/indico/env/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 178, in _get_field_class_for_data_type
    'Could not find field column of type {0}.'.format(types[0]))
marshmallow_sqlalchemy.exceptions.ModelConversionError: Could not find field column of type <class 'sqlalchemy.sql.sqltypes.NullType'>.
```

**Comment by aehernandez** [comment]
I get a similar issue when using `column_property`.

```python
  File "backend/env/local/lib/python2.7/site-packages/marshmallow/schema.py", line 118, in __new__
    dict_cls=dict_cls
  File "backend/env/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/schema.py", line 60, in get_declared_fields
    declared_fields = mcs.get_fields(converter, opts, base_fields, dict_cls)
  File "backend/env/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/schema.py", line 94, in get_fields
    dict_cls=dict_cls,
  File "backend/env/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 105, in fields_for_model
    field = base_fields.get(prop.key) or self.property2field(prop)
  File "backend/env/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 128, in property2field
    field_kwargs = self._get_field_kwargs_for_property(prop)
  File "backend/env/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 193, in _get_field_kwargs_for_property
    self._add_column_kwargs(kwargs, column)
  File "backend/env/local/lib/python2.7/site-packages/marshmallow_sqlalchemy/convert.py", line 204, in _add_column_kwargs
    if column.nullable:
  File "backend/env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 682, in __getattr__
    key)
AttributeError: Neither 'Label' object nor 'Comparator' object has an attribute 'nullable'
(env) 
```

Excluding these attributes in the schema works.

**Comment by wiz21b** [comment]
Same problem, same solution for me (using sqlalchemy-marshmallow  0.13.1, marshmallow 2.13.6, python 3). This is strange because in the change log of version 0.8.1, there's reference to a bug fix for issue #57 ...

**Comment by jebrage** [comment]
Define the Schema in this way

```
class FooSchema(ModelSchema):
    class Meta:
        model = Foo

        dump_only = (
            Foo.moo,
        )
```

I think this happens because the column property would be needed only during serialization and dumping. We shouldn't need it during deserialization and loading.

**Comment by jebrage** [comment]
This works for me.

```
class FooSchema(ModelSchema):
    moo = ma_fields.Integer(dump_only=True)

    class Meta:
        model = Foo

        fields = (
          Foo.moo.key,
        )

        dump_only = (
            Foo.moo.key,
        )
```

This seems right as we should only need the property during serialization and dumping. We shouldn't need it to deserialize and load.

**Comment by bzaks1424** [comment]
So I seem to be in the same boat - but without the same luck:

```
class Game(Base):
    def __repr__(self):
        return ("<Game >")
    __table__ = game_join

    #The only thing that seems to work is commenting out this line, which I need.
    total_tasks = column_property(
        select([func.count(Task.id)]).where(
            Task.game_id == id).correlate_except(Task)
    )
```

```
class GameSchema(BaseSchema):
    id = field_for(Game, "id", dump_only=True)
    total_tasks = field_for(Game, "total_tasks", dump_only=True) # I tried this one
    
    class Meta:
        model = Game
        #And this one.
        fields = (Game.total_tasks.key)
        dump_only = (Game.total_tasks.key)
```

Only I still get the same error.

**Comment by sloria** [comment]
This is a known issue. I'm not quite sure how to solve this since column_properties can return any type. For now, use an explicit field

```python
    total_tasks = fields.Integer(dump_only=True)
```

**Comment by sloria** [comment]
@bzaks1424 I think you're missing commas in your code snippet:

```python
        fields = (Game.total_tasks.key, )
        dump_only = (Game.total_tasks.key, )
```

that might work instead of the explicit field, if you want to go that route.

**Comment by bzaks1424** [comment]
I'd rather go with the first option (which looks cleaner, less code) but apparently psycopg2 does *not* want me to.
```
psycopg2.ProgrammingError: can't adapt type 'builtin_function_or_method'
```

And the commas didn't help me (same error as above - I wonder if this has anything to do with the fact that this is a select in a column property?)

**Comment by andreossido** [comment]
Maybe this is useful for someone:
https://github.com/tiangolo/pydantic-sqlalchemy/issues/10

**Comment by mrname** [comment]
> This is a known issue. I'm not quite sure how to solve this since column_properties can return any type. For now, use an explicit field
> 
> ```python
>     total_tasks = fields.Integer(dump_only=True)
> ```

As a small improvement, would it be worth raising an explicit exception that states the name of the property and instructions to explicitly define it instead of just blowing up? Happy to bring a PR for this, as it is slightly discouraging for someone just getting started with the module to hit cryptic SA errors IMO.

**Comment by sloria** [comment]
That's a good idea. Would be grateful if you sent a PR!

**Comment by sloria** [comment]
This is fixed in 0.28.0

**Comment by tgross35** [comment]
Heya @sloria column properties are supposed to work without error now, right? I'm still getting the above issue (`Could not find field column of type <class 'sqlalchemy.sql.sqltypes.NullType'>.`) on 0.28.0 (with SQLA 1.4.36 and marshmallow 3.15.0)
